### ISSUE TITLE
Array push_back

### ISSUE THREAD

**Issue by evelynmawrey** [aaron-ng/cs4500Assignment1#10]
Could you add a push_back function to the array class? Personally I don't feel that arrays should be treated like vectors, but that appears to be what the spec intends.

**Comment by aaron-ng** [comment]
Added the new function on this PR: https://github.com/aaron-ng/cs4500Assignment1/pull/12

Closing issue.

**Comment by DTxCode** [comment]
Hey guys, this method is a little weird given that your Array class can have "gaps" in between Objects (via put()). For example, if I have an Array `[0, 1, nullptr, 3]` and I call push_back(4), do I get `[0, 1, nullptr, 3, 4]`?

**Comment by aaron-ng** [comment]
Please raise a new issue @DTxCode since this is a closed issue that isnt being tracked. But recently we have removed the ability to pass in a parameter into the constructor so that you case should not happen. 

If there are "gaps" then yes push_back should still add a new element to the end of the list.
